notifications:
  email: false

language: node_js
node_js:
  - node

sudo: required

services:
  - docker

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash

install:
  - npm install

script:
  - docker exec -it emscripten bash -c "mkdir -p /src/build_wasm && cd /src/build_wasm && cmake ../ -DCMAKE_TOOLCHAIN_FILE=/emsdk_portable/sdk/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_BUILD_TYPE=Release -DWASM=1"
  - docker exec -it emscripten bash -c "cd /src/build_wasm && make"
  - docker exec -it emscripten bash -c "cd /src && npm run bundle:wasm"
  - docker exec -it emscripten bash -c "mkdir -p /src/build_js && cd /src/build_js && cmake ../ -DCMAKE_TOOLCHAIN_FILE=/emsdk_portable/sdk/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWASM=0"
  - docker exec -it emscripten bash -c "cd /src/build_js && make"
  - docker exec -it emscripten bash -c "cd /src && npm run bundle:js"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
