
function(ConfigureEmscriptenToolchain)
    set(CMAKE_TOOLCHAIN_FILE $ENV{EMSCRIPTEN_ROOT}/cmake/Modules/Platform/Emscripten.cmake)
    if (EXISTS ${CMAKE_TOOLCHAIN_FILE})
        message(STATUS "Found Emscripten toolchain: ${CMAKE_TOOLCHAIN_FILE}")
    else()
        message(FATAL_ERROR "Could not find Emscripten toolchain")
    endif()
    set(CMAKE_TOOLCHAIN_FILE ${CMAKE_TOOLCHAIN_FILE} PARENT_SCOPE)

    if (WIN32)
        set(EMSCRIPTEN_GENERATOR "MinGW Makefiles" PARENT_SCOPE)
    else()
        set(EMSCRIPTEN_GENERATOR "Unix Makefiles" PARENT_SCOPE)
    endif()

    if (EMSCRIPTEN)
        if (WASM)
            set(EP_SUFFIX "wasm" PARENT_SCOPE)
        else()
            set(EP_SUFFIX "js" PARENT_SCOPE)
        endif()
    endif()
endfunction()
